steps:
- name: 'gcr.io/invertible-spot-438722-m3'
  args: ['build', '-t', 'cicd1image:v1.0', '.']
- name: 'gcr.io/invertible-spot-438722-m3'
  args: ['push', 'cicd1image']
options:
  logging: CLOUD_LOGGING_ONLY