steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/invertible-spot-438722-m3/cicd1image:v1.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/invertible-spot-438722-m3/cicd1image:v1.0']
options:
  logging: CLOUD_LOGGING_ONLY