steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/invertible-spot-438722-m3/cicd1image:v2.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/invertible-spot-438722-m3/cicd1image']
options:
  logging: CLOUD_LOGGING_ONLY